{% set version = "4.4.0" %} # semver: (x.y.z)
{% set x,y,z = version.split('.') %}
{% set version_ffmpeg_style = x ~ '.' ~ y if z == "0" else version %}

package:
  name: ffmpeg
  version: {{ version }}

source:
  - url: https://ffmpeg.org/releases/ffmpeg-{{ version_ffmpeg_style }}.tar.gz  # [not win]
    sha256: a4abede145de22eaf233baa1726e38e137f5698d9edd61b5763cd02b883f3c7c  # [not win]

  - url: https://github.com/GyanD/codexffmpeg/releases/download/{{ version_ffmpeg_style }}/ffmpeg-{{ version_ffmpeg_style }}-full_build-shared.zip  # [win]
    sha256: ba6fa745b970ebcadae265b0474290a247deebae1bf835f5c13b352661c2d213  # [win]

build:
  number: 0
  run_exports:
  # seems to be major version compatibility
  # https://abi-laboratory.pro/tracker/timeline/ffmpeg/
    - {{ pin_subpackage('ffmpeg', max_pin='x') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - pkg-config  # [not win]
    - libtool  # [not win]
    - nasm  # [not win]
    - lame  # [not win]
    - make  # [not win]
  host:
    - bzip2  # [not win]
    - freetype  # [not win]
    - gnutls  # [not win]
    - libiconv  # [osx]
    - x264  # [not win]
    - zlib  # [not win]
    - openh264  # [not win]
    - lame  # [not win]
    - gmp  # [unix]
  run:
    - bzip2  # [not win]
    - freetype  # [not win]
    - gnutls  # [not win]
    - openh264  # [not win]
    - lame  # [not win]
    - gmp  # [unix]

test:
  commands:
    - ffmpeg --help
    - ffmpeg -loglevel panic -protocols | grep "https"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "libmp3lame"  # [not win]
    - ffmpeg -loglevel panic -codecs | grep "DEVI.S zlib"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "DEV.LS h264"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "libx264"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "libopenh264"  # [unix]
    - ffmpeg -loglevel panic -codecs | grep "libaom"  # [unix]
    # Verify dynamic libraries on all systems
    {% set ffmpeg_libs = [
        "avcodec",
        "avdevice",
        "swresample",
        "postproc",
        "avfilter",
        "swresample",
        "avcodec",
        "avformat",
        "swscale",
        "avresample",
        "aom",
    ] %}
    {% for each_ffmpeg_lib in ffmpeg_libs %}
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ each_ffmpeg_lib }}.so     # [linux]
    {% endfor %}

about:
  home: http://www.ffmpeg.org/
  license: GPL-3.0-or-later
  license_file: COPYING.GPLv3  # [unix]
  summary: Cross-platform solution to record, convert and stream audio and video.

extra:
  recipe-maintainers:
    - danielballan
    - jakirkham
    - 183amir
    - patricksnape
    - ocefpaf
    - sdvillal
    - carlodri
